name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i
      - run: npm run build
      - uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "discord-reminder-bot-eu"
          heroku_email: "xavicaromiro@gmail.com"
          appdir: "dist"
          healthcheck: "https://discord-reminder-bot-eu.herokuapp.com/health"
          rollbackonhealthcheckfailed: true
          procfile: "worker: node dist/index.js"
        env:
          TOKEN: ${{secrets.FIREBASE_API_KEY}}
