name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add remote origin
        run: git remote add heroku-remote https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - name: Unshallow
        run: git fetch --all --unshallow
      - name: Deploy to Heroku
        run: git push heroku-remote HEAD:main -f
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'
      - name: npm install
        run: npm i
      - name: npm run build
        run: npm run build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          appdir: dist
          docker_heroku_process_type: worker
          # healthcheck: "https://discord-reminder-bot-eu.herokuapp.com/health"
          # rollbackonhealthcheckfailed: true
          # procfile: "worker: node dist/index.js"
        # env:
          # TOKEN: ${{secrets.FIREBASE_API_KEY}}
